name: ai-dungeon-cli-env
dependencies:
- python=3
- pip
- requests=2.*
- PyYAML=5.*
- pip:
    # - git+git://github.com/graphql-python/gql@v3.0.0a1#egg=gql
    - gql >= v3.0.0a1
    - pyreadline >= 2.1;platform_system=='Windows'
